// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0MeR17bBpNkE_k02CXno6q61KxG9FDqs',
    appId: '1:807630132367:web:0b065c452a74ab6ee20cfa',
    messagingSenderId: '807630132367',
    projectId: 'flutter-ecom-d6c45',
    authDomain: 'flutter-ecom-d6c45.firebaseapp.com',
    storageBucket: 'flutter-ecom-d6c45.firebasestorage.app',
    measurementId: 'G-RJEG52FHNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj_msoViFKvM9RFc47GqoZRLfMk1uYI3g',
    appId: '1:807630132367:android:8d5fa48fd6f4f076e20cfa',
    messagingSenderId: '807630132367',
    projectId: 'flutter-ecom-d6c45',
    storageBucket: 'flutter-ecom-d6c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuoFL5eKi97uvyJcBlwYL9pcvLdiIxf74',
    appId: '1:807630132367:ios:8f2013a36f8d48b2e20cfa',
    messagingSenderId: '807630132367',
    projectId: 'flutter-ecom-d6c45',
    storageBucket: 'flutter-ecom-d6c45.firebasestorage.app',
    iosClientId: '807630132367-i4ggd0j92n9e7303ulme69h9b71v01ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuoFL5eKi97uvyJcBlwYL9pcvLdiIxf74',
    appId: '1:807630132367:ios:8f2013a36f8d48b2e20cfa',
    messagingSenderId: '807630132367',
    projectId: 'flutter-ecom-d6c45',
    storageBucket: 'flutter-ecom-d6c45.firebasestorage.app',
    iosClientId: '807630132367-i4ggd0j92n9e7303ulme69h9b71v01ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0MeR17bBpNkE_k02CXno6q61KxG9FDqs',
    appId: '1:807630132367:web:e8383fcd38ece8bbe20cfa',
    messagingSenderId: '807630132367',
    projectId: 'flutter-ecom-d6c45',
    authDomain: 'flutter-ecom-d6c45.firebaseapp.com',
    storageBucket: 'flutter-ecom-d6c45.firebasestorage.app',
    measurementId: 'G-YXL9XTH0TC',
  );
}
